name: drugMR CI

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pipeline test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "26.04.0"

      - name: Run pipeline
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,docker -params-file tests/data/params.yaml

      - name: Check results
        run: python tests/check_results.py

      - name: Upload logs after a failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-test-logs
          path: |
            .nextflow.log
            tests/output/
